# Generated by Django 4.0.2 on 2023-11-27 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cpj', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='correo',
            field=models.EmailField(max_length=255),
        ),
    ]
